import test from 'node:test';
import assert from 'node:assert/strict';
import {watchAccountability,readAccountability,publishOperationsUpdate} from '../src/services/accountability.js';
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function fixture(load){let hidden=false,delays=[],result=[],errors=[],timers=new Map(),next=0;const watcher=watchAccountability({load,onData:(...data)=>result.push(data),onError:error=>errors.push(error),visible:()=>!hidden,schedule:(fn,delay)=>{delays.push(delay);timers.set(++next,fn);return next;},cancel:id=>timers.delete(id),now:()=>123});return {watcher,result,errors,delays,timers,hide:value=>{hidden=value;watcher.visibilityChanged();}};}
test('accountability polls every 30 seconds and manual refresh cancels the timer',async()=>{let calls=0;const f=fixture(async()=>({status:++calls}));await tick();assert.deepEqual(f.delays,[30000]);await f.watcher.refresh();assert.equal(calls,2);assert.equal(f.timers.size,1);f.watcher.close();assert.equal(f.timers.size,0);});
test('one pending read, aborted cleanup and late results suppressed',async()=>{let complete,signal,calls=0;const f=fixture(s=>{calls++;signal=s;return new Promise(resolve=>complete=resolve);});await f.watcher.refresh();assert.equal(calls,1);f.watcher.close();assert(signal.aborted);complete({status:'resolved'});await tick();assert.equal(f.result.length,0);assert.equal(f.timers.size,0);});
test('hidden detail pauses and visibility resume refreshes',async()=>{let calls=0;const f=fixture(async()=>++calls);await tick();f.hide(true);await f.watcher.refresh();assert.equal(calls,1);assert.equal(f.timers.size,0);f.hide(false);await tick();assert.equal(calls,2);f.watcher.close();});
test('errors back off, auth/ownership denial stops polling',async()=>{const f=fixture(async()=>{throw {code:'offline'};});await tick();assert.equal(f.delays[0],60000);await f.watcher.refresh();assert.equal(f.delays[1],120000);f.watcher.close();const denied=fixture(async()=>{throw {code:'PT403'};});await tick();assert.equal(denied.timers.size,0);await denied.watcher.refresh();assert.equal(denied.errors.length,1);denied.watcher.close();});
test('last successful data survives a failed refresh through consumer callbacks',async()=>{let calls=0;const f=fixture(async()=>{if(++calls===2)throw Error();return {status:'assigned'};});await tick();await f.watcher.refresh();assert.equal(f.result.length,1);assert.equal(f.result[0][1],123);assert.equal(f.errors.length,1);f.watcher.close();});
test('own-report reader uses safe RPC and abort signal',async()=>{let input,signal;const controller=new AbortController();const client={rpc:(name,args)=>{input={name,args};return {abortSignal:s=>{signal=s;return Promise.resolve({data:{status:'reported'}});}};}};assert.equal((await readAccountability(client,'report',{signal:controller.signal})).status,'reported');assert.deepEqual(input,{name:'nigraan_read_accountability',args:{incident:'report'}});assert.equal(signal,controller.signal);});
test('message publication uses idempotency receipt and atomic resolution RPC',async()=>{let input;const client={rpc:async(name,args)=>{input={name,args};return {data:4};}};await publishOperationsUpdate(client,{incident:'report',body:' Done ',requestId:'receipt',resolution:true,expectedStatus:'in_progress'});assert.deepEqual(input,{name:'nigraan_resolve_with_message',args:{incident:'report',body:'Done',request_id:'receipt',expected_status:'in_progress'}});await assert.rejects(publishOperationsUpdate(client,{body:' ',requestId:'receipt'}));await assert.rejects(publishOperationsUpdate(client,{body:'x'.repeat(1001)}));});
