import useContext from './environment';
import {rows as base} from '../map-browser/client';
export const rows=base.map((row,index)=>({...row,status:index===1?'in_progress':row.status,reported_at:new Date(Date.now()-(index+1)*3600000).toISOString()}));
export const configurationError='';
export const fixtureChanges=[{id:'published-update',incident_id:rows[0].id,kind:'update',submission_state:'published',published_at:new Date(Date.now()-60000).toISOString()},{id:'published-edit',incident_id:rows[1].id,kind:'edit',submission_state:'published',published_at:new Date(Date.now()-120000).toISOString()},{id:'hidden-draft',incident_id:rows[0].id,kind:'update',submission_state:'draft',published_at:new Date(Date.now()-60000).toISOString()}];
function queryFor(table){let metadata=false,selected,ids=null,state=null,start=0,end=999,from=null,to=null,signal;return {select(columns){metadata=columns==='id,incident_id,kind,published_at';return this;},eq(field,value){if(field==='id')selected=value;if(field==='submission_state')state=value;return this;},in(field,value){ids=value;return this;},lt(field,value){to=value;return this;},gte(field,value){from=value;return this;},order(){return this;},limit(n){end=n-1;return this;},range(a,b){start=a;end=b;return this;},abortSignal(value){signal=value;return this;},maybeSingle:async()=>({data:rows.find(r=>r.id===selected),error:null}),then(resolve){return new Promise(done=>{if(window.analyticsFixtureDelay)window.analyticsFixtureStarted=(window.analyticsFixtureStarted||0)+1;const finish=()=>{if(signal?.aborted){window.analyticsFixtureAborted=(window.analyticsFixtureAborted||0)+1;done({error:new Error('Fixture cancelled')});return;}if(table==='nigraan_citizen_changes'&&window.analyticsFixtureFailure){done({error:new Error('Fixture read failure')});return;}const data=table==='incidents'?rows.filter(r=>(!selected||r.id===selected)&&(!state||r.submission_state===state)).slice(start,end+1):table==='nigraan_citizen_changes'&&metadata?fixtureChanges.filter(c=>(!ids||ids.includes(c.incident_id))&&(!state||c.submission_state===state)&&(!to||c.published_at<to)&&(!from||c.published_at>=from)).slice(start,end+1).map(({id,incident_id,kind,published_at})=>({id,incident_id,kind,published_at})):[];done({data,error:null});};setTimeout(finish,window.analyticsFixtureDelay||0);signal?.addEventListener('abort',()=>{window.analyticsFixtureAborted=(window.analyticsFixtureAborted||0)+1;done({error:new Error('Fixture cancelled')});},{once:true});}).then(resolve);}};}
export const supabase={functions:{invoke:async name=>name==='city-context'?{data:{...useContext().data,version:1,context_only:true,city:{id:'karachi'}}}:{error:new Error('No provider in fixture')}},auth:{getUser:async()=>({data:{user:{id:'fixture-user'}}})},from:queryFor,storage:{from:()=>({createSignedUrl:async()=>({error:new Error('No evidence in test fixture')})})},rpc:async(name,args)=>{if(name==='is_approved_operations')return {data:!window.agentFixtureDenied,error:null};if(name!=='nigraan_update_incident_status')return {error:new Error('Test fixture has no provider')};const row=rows.find(r=>r.id===args.incident);if(!row||row.status!==args.expected_status)return {error:new Error('Stale fixture')};row.status=args.next_status;return {data:row.id,error:null};}};
export const requireSupabase=()=>supabase;


