import test from "node:test";
import assert from "node:assert/strict";
import {createServer} from "node:http";
import {once} from "node:events";
import {resolve} from "node:path";
import {pathToFileURL} from "node:url";
import {createApp} from "../src/handler.js";
import {MemoryStore} from "../src/state.js";
import {fixtures,upstream} from "./helpers.js";
test("simulator real SDK over HTTP: consent/PKCE, five tools, read/ref, revoke", async t => {
  const {createSimulatorSession,SIMULATOR_CLIENT_ID}=await import(pathToFileURL(resolve("../../src/services/mcpSimulator.js")).href);
  const http=createServer();http.listen(0,"127.0.0.1");await once(http,"listening");
  t.after(()=>new Promise<void>(r=>http.close(()=>r())));
  const origin=`http://127.0.0.1:${(http.address() as {port:number}).port}`;
  const config={origin,consentUrl:"https://nigraanos.netlify.app/",clientId:SIMULATOR_CLIENT_ID,clientName:"NigraanOS Alexa+ Simulator",redirectUri:"https://nigraanos.netlify.app/agent-callback"};
  const f=fixtures(),store=new MemoryStore(),{app}=createApp(config,f.factory,store);
  http.on("request",app);
  const map=new Map<string,string>(),wire: {url:string; authorization:string}[]=[];
  const session=createSimulatorSession({storage:{getItem:(k:string)=>map.get(k)||null,setItem:(k:string,v:string)=>map.set(k,v),removeItem:(k:string)=>map.delete(k)},fetcher:async(url: any,options: any)=>{
    wire.push({url:String(url),authorization:new Headers(options?.headers).get("authorization")||""});return fetch(url,options);
  }});
  t.after(()=>session.disconnect());
  const clientConfig={endpoint:origin,clientId:config.clientId,redirectUri:config.redirectUri};
  const authorization=await session.begin(clientConfig,"owner");
  const start=await fetch(authorization,{redirect:"manual"});assert.equal(start.status,302);
  const tx=new URLSearchParams(new URL(start.headers.get("location")!).hash.split("?")[1]).get("transaction")!;
  const credential=upstream();
  const inspection=await fetch(origin+"/delegation/request?transaction="+tx,{headers:{Authorization:"Bearer "+credential}});
  assert.equal(inspection.status,200);const request=await inspection.json() as any;
  const decision=await fetch(origin+"/delegation/decision",{method:"POST",headers:{Authorization:"Bearer "+credential,"Content-Type":"application/json"},body:JSON.stringify({transaction:tx,state:request.state,decision:"approve"})});
  assert.equal(decision.status,200);const {redirect}=await decision.json() as any;
  await session.finish(redirect,clientConfig,"owner");assert.equal(session.snapshot().status,"connected");assert.equal(map.size,0);
  const result=await session.run("get_city_status");assert.equal(result.facts.submitted,2);
  const detail=await session.run("get_incident_details",{ref:"I1"});assert.equal(detail.incidents[0].ref,"I1");
  for(const n of ["get_urgent_incidents","get_city_conditions","get_incident_activity"])await session.run(n);
  const {createInvestigationController}=await import(pathToFileURL(resolve("../../src/services/incidentInvestigation.js")).href);
  const investigation=await createInvestigationController({tools:session.facade(()=>{})}).run();
  assert.equal(investigation.status,"complete");
  assert.equal(investigation.coverage.inspected,2);
  assert.equal(investigation.sources.length,7);
  assert.ok(!JSON.stringify(investigation).includes("PRIVATE_"));
  assert.ok(!JSON.stringify(result).includes("PRIVATE_"));
  const bearer=wire.find(v=>v.url.endsWith("/mcp"))!.authorization;
  assert.ok(bearer.startsWith("Bearer "));assert.notEqual(bearer,"Bearer "+credential);
  await session.disconnect();
  const rejected=await fetch(origin+"/mcp",{method:"POST",headers:{Authorization:bearer,"Content-Type":"application/json",Accept:"application/json, text/event-stream"},body:JSON.stringify({jsonrpc:"2.0",id:1,method:"tools/list",params:{}})});
  assert.equal(rejected.status,401);
});
