import {useEffect,useRef,useState} from 'react';
import {requireSupabase} from '../services/supabase';
import {consentRequest} from '../services/agentConsent';
export function AgentConsentView({request,busy,error,onDecision}){
 return <main className="citizen-main"><section className="panel"><span className="eyebrow">MCP AUTHORIZATION</span><h2>Approve read-only Operations access?</h2><p>Approve a separate read-only grant. The simulator is not connected to the official Alexa+ backend.</p>{error&&<p role="alert">{error}</p>}{!request&&!error&&<p role="status">Checking authorization request…</p>}{request&&<><h3>{request.clientName}</h3><p>Requested scope: <strong>{request.scope}</strong></p><ul>{request.capabilities.map(item=><li key={item}>{item}</li>)}</ul><p>No operational changes, Citizen prose, identities, evidence, exact locations or permanent conversation memory are included. Access ends within ten minutes, or when the current upstream credential expires.</p><p>Your Supabase credential is supplied only to the authorization broker, never as the simulator's MCP bearer. AWS storage encrypts delegated credentials; local development uses temporary process memory.</p><button className="primary" disabled={busy||Boolean(error)} onClick={()=>onDecision('approve')}>Approve read access</button><button className="secondary" disabled={busy||Boolean(error)} onClick={()=>onDecision('deny')}>Deny</button></>}{busy&&<p role="status">Processing authorization…</p>}</section></main>;
}
export default function AgentConsentPage({route,userId}){
 const [request,setRequest]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const decisionController=useRef(null),active=useRef(true),locked=useRef(false);
 const transaction=new URLSearchParams(route.split('?')[1]||'').get('transaction')||'';
 useEffect(()=>{active.current=true;locked.current=false;const controller=new AbortController();setRequest(null);setError('');consentRequest(requireSupabase(),'/delegation/request',{transaction,signal:controller.signal}).then(value=>{if(!controller.signal.aborted)setRequest(value);}).catch(()=>{if(!controller.signal.aborted)setError('Authorization request is unavailable, expired, or not permitted.');});return()=>{active.current=false;controller.abort();decisionController.current?.abort();};},[transaction,userId]);
 useEffect(()=>{if(!request)return;const timer=setTimeout(()=>{setRequest(null);setError('Authorization request expired. Start a new request.');decisionController.current?.abort();},Math.max(0,Date.parse(request.expiresAt)-Date.now()));return()=>clearTimeout(timer);},[request]);
 async function decide(decision){if(locked.current||!request||error)return;locked.current=true;setBusy(true);const controller=new AbortController();decisionController.current=controller;try{const result=await consentRequest(requireSupabase(),'/delegation/decision',{transaction,state:request.state,decision,signal:controller.signal});if(active.current&&!controller.signal.aborted)window.location.assign(result.redirect);}catch{if(active.current&&!controller.signal.aborted){setError('Authorization could not be completed. Start a new request.');setRequest(null);}}finally{if(active.current){setBusy(false);locked.current=false;}}}
 return <AgentConsentView request={request} busy={busy} error={error} onDecision={decide}/>;
}
