import {useEffect,useRef,useState} from 'react';
import useNigraanAgent from '../hooks/useNigraanAgent';
import {AGENT_PROMPTS} from '../utils/agentConversation';
import {displayStatus} from '../data/reportOptions';
import {AGENT_VIEWS} from '../services/agentTools';
const format=value=>new Date(value).toLocaleString('en-GB',{timeZone:'Asia/Karachi'});
const label=value=>value.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());
function Result({entry,busy,onSubmit}){
  const {result,referenceVersion}=entry;
  return <div className="agent-result"><span className={'agent-kind agent-kind-'+result.kind.toLowerCase()}>{result.kind}</span><h3>{result.headline}</h3><small>Read snapshot: {format(result.snapshotAt)} PKT</small>
    {result.facts&&<dl className="agent-facts">{Object.entries(result.facts).map(([key,value])=><div key={key}><dt>{label(key)}</dt><dd>{value===null?'Unavailable':value}</dd></div>)}</dl>}
    {result.notice&&<p className="agent-caveat">{result.notice}</p>}
    {result.incidents&&(!result.incidents.length?<p>No incidents in this result. This does not establish that the city is safe.</p>:<div className="agent-incidents">{result.incidents.map(i=><article key={i.ref}><h4>{i.ref} · {displayStatus(i.category)}</h4><p>{displayStatus(i.status)} · Recorded priority: {displayStatus(i.priority)}</p><small>{i.ageHours===null?'Report age unavailable':i.ageHours.toLocaleString('en-GB',{maximumFractionDigits:1})+' hr since report start'}</small>{i.reasons&&<div className="attention-reasons">{i.reasons.map(r=><span key={r}>{r}</span>)}</div>}<div className="agent-card-actions"><button disabled={busy} className="secondary" onClick={()=>onSubmit('Tell me more about '+i.ref,{tool:'get_incident_details',input:{ref:i.ref,referenceVersion}})}>Details</button><button disabled={busy} className="text-button" onClick={()=>onSubmit('Open '+i.ref,{tool:'navigate_to_incident',input:{ref:i.ref,referenceVersion}})}>Open Incidents →</button></div></article>)}</div>)}
    {result.activity&&(!result.activity.length?<p>No published Citizen activity in the previous 24 hours.</p>:<ul className="agent-activity">{result.activity.map((a,n)=><li key={n}>{a.ref} · Citizen {a.kind} · {format(a.publishedAt)} PKT</li>)}</ul>)}
    {result.omitted>0&&<p className="muted">{result.omitted} additional records omitted from this bounded result. Open the existing Operations views for broader review.</p>}
    {result.context&&<><div className="agent-context">{[['weather','Weather'],['air','Air quality']].map(([key,title])=>{const part=result.context[key];return <article key={key}><h4>{title} · {part.status}</h4><p>{part.status==='unavailable'?'Context unavailable':key==='weather'?(part.temperatureC??'Unavailable')+' °C · Precipitation '+(part.precipitationMm??'Unavailable')+' mm / '+(part.intervalSeconds??'Unavailable')+' seconds':'Modeled US AQI: '+(part.aqi??'Unavailable')}</p><small>{part.source}<br/>Valid: {part.validAt?format(part.validAt):'Unavailable'}<br/>Fetched: {part.fetchedAt?format(part.fetchedAt):'Unavailable'}</small></article>;})}</div><p className="agent-caveat">{result.context.disclaimer}</p></>}
  </div>;
}
export function NigraanAgentView({thread,busy,tool,onSubmit,onClear,connection={status:'disconnected',error:''},onConnect,onDisconnect}){
  const [input,setInput]=useState('');
  const log=useRef(null);
  useEffect(()=>{if(log.current)log.current.scrollTop=log.current.scrollHeight;},[thread,busy]);
  function send(event){event.preventDefault();if(input.trim()){onSubmit(input);setInput('');}}
  return <main className="dashboard agent-page">
    <div className="page-heading"><div><span className="eyebrow accent">OPERATIONS · READ TOOLS</span><h2>Nigraan Agent</h2><p>Simulated Alexa+ experience for the Amazon Developer Hackathon.</p></div><button className="secondary" onClick={onClear}>Clear conversation</button></div>
    <p className="agent-disclosure">Text simulation · Not connected to Alexa+. Deterministic supported intents read authorized NigraanOS data. No AI planner, operational writes or permanent conversation memory.</p>
    <section className="panel" aria-label="MCP connection"><strong>Read-only MCP · {connection.status}</strong>{connection.error&&<p role="alert">{connection.error}</p>}<p>Simulated Alexa+ experience. Connected reads use the real MCP backend; this is not an official Alexa+ integration.</p>{connection.status==='connected'?<button className="secondary" onClick={onDisconnect}>Disconnect and revoke read access</button>:<button className="primary" disabled={busy||['authorizing','connecting'].includes(connection.status)} onClick={onConnect}>Connect read access</button>}</section>
    <div className="agent-workspace"><aside className="panel agent-guide"><h3>Ask, inspect, navigate</h3><p>Start with a city read. Follow up with “Tell me more about the first one.”</p><div className="agent-prompts">{AGENT_PROMPTS.map(prompt=><button className="secondary" disabled={busy} key={prompt} onClick={()=>onSubmit(prompt)}>{prompt}</button>)}</div><h4>Open workspace</h4>{Object.keys(AGENT_VIEWS).map(view=><button className="text-button" disabled={busy} key={view} onClick={()=>onSubmit('Open '+view,{tool:'navigate_to_view',input:{view}})}>{view} →</button>)}<p className="muted">FACT: recorded data.<br/>CONTEXT: modeled conditions.<br/>INTERPRETATION: AI reasoning, not generated here.<br/>SUGGESTED ACTION: human judgment, never automatic.</p></aside>
      <section className="panel agent-conversation" aria-label="Agent conversation"><div ref={log} className="agent-thread" role="log" aria-live="polite" aria-relevant="additions">{!thread.length&&<div className="agent-empty"><span className="agent-orbit" aria-hidden="true">◎</span><h3>What should we review?</h3><p>Read current city status, urgent candidates, published activity or modeled conditions. Use current I-references to inspect a result.</p></div>}{thread.map(entry=><article key={entry.id} className={'agent-message agent-message-'+entry.role+(entry.error?' agent-message-error':'')}><span className="eyebrow">{entry.role==='operator'?'Operator':'Nigraan Agent'}</span>{entry.text&&<p dir="auto">{entry.text}</p>}{entry.tool&&<p className="agent-tool">Completed · {entry.tool} · {entry.result.kind==='NAVIGATION'?'Client navigation':'Authorized read'}</p>}{entry.result&&<Result entry={entry} busy={busy} onSubmit={onSubmit}/>}</article>)}{busy&&<p role="status" className="agent-tool">Reading · {tool||'Resolving request'}…</p>}</div>
      <form className="agent-input" onSubmit={send}><label htmlFor="agent-request">Operator request</label><textarea id="agent-request" value={input} onChange={e=>setInput(e.target.value)} maxLength={600} disabled={busy} rows={2} placeholder="What needs attention right now?"/><div><small>References expire after 5 minutes. Do not enter Citizen names, contact details or private report text.</small><button className="primary" disabled={busy||!input.trim()} type="submit">{busy?'Reading…':'Send request'}</button></div></form></section>
    </div>
  </main>;
}
export default function NigraanAgent(props){const agent=useNigraanAgent(props);return <NigraanAgentView {...agent} onSubmit={agent.submit} onClear={agent.clear} onConnect={agent.connect} onDisconnect={agent.disconnect}/>;}
