import {useMemo,useState} from 'react';
import {calculateAnalytics,PERIODS,analyticsWindow} from '../utils/operationsAnalytics';
import useAnalyticsActivity from '../hooks/useAnalyticsActivity';
import {displayStatus,reportCategories} from '../data/reportOptions';
const time=value=>new Date(value).toLocaleString('en-GB',{timeZone:'Asia/Karachi',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'})+' PKT';
const label=key=>key==='unknown'?'Unknown / legacy':reportCategories.find(c=>c.id===key)?.label||displayStatus(key);
const signed=n=>(n>0?'+':'')+n;
function Bars({title,items,note}){
  const maximum=Math.max(1,...items.map(item=>item.count));
  return <section className="panel analytics-chart"><h3>{title}</h3>{note&&<p className="analytics-note">{note}</p>}
    <div className="analytics-bars" aria-label={title}>{items.map(item=><div key={item.key} tabIndex={0} className="analytics-bar-row" aria-label={label(item.key)+': '+item.count+' reports'}><span>{label(item.key)}</span><div className="analytics-bar-track" aria-hidden="true"><i style={{width:100*item.count/maximum+'%'}}/></div><strong>{item.count}</strong><span className="analytics-tooltip" role="tooltip">{label(item.key)}: {item.count} reports</span></div>)}</div>
    <details className="analytics-table-fallback"><summary>View count table</summary><table><caption>{title}</caption><thead><tr><th>Group</th><th>Reports</th></tr></thead><tbody>{items.map(item=><tr key={item.key}><th scope="row">{label(item.key)}</th><td>{item.count}</td></tr>)}</tbody></table></details>
  </section>;
}
function Volume({items,total}){
  const max=Math.max(1,...items.map(i=>i.count)),width=Math.max(320,items.length*28),height=150;
  const [focused,setFocused]=useState(null);
  return <section className="panel analytics-chart analytics-volume"><h3>Report Volume</h3><p className="analytics-note">Report starts in each time interval. Intervals are start-inclusive and end-exclusive.</p>
    {!total&&<p className="analytics-empty">No reports started in this selected period.</p>}
    {!!total&&!items.length&&<p className="analytics-empty">No valid report-start timestamps are available for the timeline.</p>}
    {!!items.length&&<><svg viewBox={'0 0 '+width+' '+(height+32)} role="group" aria-label="Report volume by time interval" className="analytics-timeline">{items.map((item,n)=>{const slot=width/items.length,x=n*slot+slot/2,bh=item.count/max*(height-12);return <g key={item.from} tabIndex={0} onFocus={()=>setFocused(item)} onBlur={()=>setFocused(null)} onMouseEnter={()=>setFocused(item)} onMouseLeave={()=>setFocused(null)} aria-label={time(item.from)+' to '+time(item.to)+': '+item.count+' reports'}><title>{time(item.from)+' → '+time(item.to)+': '+item.count+' reports'}</title><rect x={x-slot*.3} y={height-bh} width={slot*.6} height={bh} rx="2"/><line x1={x-slot*.3} x2={x+slot*.3} y1={height} y2={height}/>{(n%Math.max(1,Math.ceil(items.length/6))===0||n===items.length-1)&&<text x={x} y={height+20} textAnchor="middle">{new Date(item.from).toLocaleString('en-GB',{timeZone:'Asia/Karachi',...(items[0].to-items[0].from<86400000?{hour:'2-digit',minute:'2-digit'}:{day:'2-digit',month:'short',...(items.at(-1).to-items[0].from>365*86400000?{year:'2-digit'}:{})})})}</text>}</g>;})}</svg><p className="analytics-focused-bucket" role="status">{focused?time(focused.from)+' → '+time(focused.to)+': '+focused.count+' reports':'Focus or hover a bucket to inspect its interval.'}</p><p className="analytics-note">Focus a time bucket for its exact interval and count, or open the table below. Rolling-day buckets are anchored to the snapshot, not midnight.</p></>}
    <details className="analytics-table-fallback"><summary>View timeline table</summary><table><caption>Report starts by interval · PKT</caption><thead><tr><th>Interval [start, end)</th><th>Reports</th></tr></thead><tbody>{items.map(i=><tr key={i.from}><th scope="row">{time(i.from)} → {time(i.to)}</th><td>{i.count}</td></tr>)}</tbody></table></details>
  </section>;
}
export function AnalyticsView({data,period,onPeriod,onRefresh,loading,error,activityStatus,onSelect}){
  const unavailable=Boolean(error)||!data;
  return <main className="dashboard operations-analytics">
    <header className="analytics-header"><div><h2>Operations Analytics</h2><p className="muted">Authorized submitted incidents · Current recorded facts</p></div><button className="secondary" disabled={loading} onClick={onRefresh}>{loading?'Refreshing…':'Refresh analytics'}</button></header>
    <div className="analytics-period"><label>Report period<select value={period} onChange={e=>onPeriod(e.target.value)}>{PERIODS.map(([key,title])=><option key={key} value={key}>{title}</option>)}</select></label><div><p>{data?data.window.from===null?'All available report records; published activity before '+time(data.window.to)+' · No lower time bound':time(data.window.from)+' → '+time(data.window.to)+' · [start, end)':'Waiting for an authorized snapshot.'}</p>{data&&<small>Snapshot endpoint: {time(data.window.to)} · Browser refresh snapshot</small>}</div></div>
    <p className="analytics-note">Report-start time is recorded before publication. Status and priority are current at refresh; these charts do not describe historical workflow transitions.</p>
    {error&&<p className="error" role="alert">Incident analytics unavailable. Refresh or check your Operations access.</p>}
    <section className="analytics-summary" aria-label="Analytics summary">{[['Reports started',data?.total,'Reports in the selected report cohort.'],['Currently unresolved',data?.unresolved,'Selected cohort · Current status is not resolved.'],['Currently resolved',data?.resolved,'Selected cohort · Current status is resolved.'],['Citizen updates',data?.updates,'Published update events in the selected time window, including older readable reports.']].map(([title,count,note],n)=><article key={title}><span>{title}</span><strong>{unavailable?error?'Unavailable':'Loading…':n===3&&activityStatus!=='ready'?activityStatus==='loading'?'Loading…':'Unavailable':count}</strong><small>{note}</small></article>)}</section>
    {!unavailable&&<>
      {!!data.invalidDates&&<p className="analytics-note" role="status">{data.invalidDates} reports have missing, invalid or future report-start timestamps. They remain in all-data counts and applicable backlog groups, but are excluded from time calculations.</p>}
      <Volume key={data.window.period+':'+data.window.to} items={data.timeline} total={data.total}/>
      <div className="analytics-distributions"><Bars title="Category" items={data.category} note="Current recorded categories. Citizen edits may reclassify past reports."/><Bars title="Current status" items={data.status} note="Current workflow snapshot for the selected report cohort."/><Bars title="Recorded priority" items={data.priority} note="Recorded values, not verified severity. New reports start at normal."/></div>
      <section className="panel analytics-backlog"><div className="analytics-section-heading"><h3>Current Backlog · All Report Ages</h3><span>{data.backlogCount} unresolved</span></div><p className="analytics-note">All authorized unresolved incidents, independent of the selected report period. Age is since report start.</p><div className="analytics-backlog-grid"><Bars title="Age since report start" items={data.ageBands}/><div className="analytics-oldest"><h4>Oldest unresolved</h4>{!data.oldest.length&&<p className="analytics-empty">No unresolved incidents with a valid report-start time.</p>}{data.oldest.map(i=><article key={i.id}><h4 dir="auto">{i.title}</h4><p>{label(DOMAINS_CATEGORY(i.category))} · {displayStatus(i.status)||'Unknown / legacy'} · Recorded priority: {displayStatus(i.priority)||'Unknown / legacy'}</p><small>{i.ageHours.toLocaleString('en-GB',{maximumFractionDigits:1})} hr since report start</small><button className="text-button" onClick={()=>onSelect(i.id)}>View Incident →</button></article>)}</div></div></section>
      <section className="panel analytics-activity"><h3>Recent Citizen Activity</h3><p className="analytics-note">Published edits and updates during the selected activity window, including older readable reports.</p>{activityStatus!=='ready'?<p role="status" className={activityStatus==='unavailable'?'error':'muted'}>{activityStatus==='loading'?'Loading complete activity metadata…':'Citizen activity unavailable. Refresh to retry; counts are not assumed to be zero.'}</p>:!data.recent.length?<p className="analytics-empty">No published Citizen edits or updates in this period.</p>:data.recent.map(c=><article key={c.id}><div><strong>{c.kind==='edit'?'Citizen edit':'Citizen update'}</strong><p dir="auto">{c.incident.title} · {label(DOMAINS_CATEGORY(c.incident.category))}</p><time dateTime={c.published_at}>{time(c.published_at)}</time></div><button className="text-button" onClick={()=>onSelect(c.incident_id)}>View Incident →</button></article>)}</section>
      <section className="panel analytics-comparison"><h3>Category comparison</h3>{data.comparison?<><p className="analytics-note">Current recorded category: selected period versus the immediately preceding equal-duration period ({time(data.window.from-data.window.duration)} → {time(data.window.from)}). Citizen edits may reclassify reports.</p><table><caption>Deterministic report counts · Not a measure of worsening conditions</caption><thead><tr><th>Category</th><th>Current</th><th>Previous</th><th>Difference</th><th>Context</th></tr></thead><tbody>{data.comparison.map(c=><tr key={c.key}><th scope="row">{label(c.key)}</th><td data-label="Current">{c.current}</td><td data-label="Previous">{c.previous}</td><td data-label="Difference">{signed(c.difference)}</td><td data-label="Context">{c.percentage!==null?signed(Number(c.percentage.toFixed(1)))+'%':c.smallSample?'Small sample':'Counts only'}</td></tr>)}</tbody></table><p className="analytics-note">Percent change appears only with at least 10 reports in each period. Small-sample labels are presentation rules, not statistical significance.</p></>:<p className="analytics-empty">No previous-period comparison for All available data.</p>}</section>
    </>}
    {!data&&!error&&<p role="status">Loading authorized incident analytics…</p>}
  </main>;
}
const DOMAINS_CATEGORY=value=>reportCategories.some(c=>c.id===value)?value:'unknown';
export default function OperationsAnalytics({feed,accountId,onSelect}){
  const [period,setPeriod]=useState('7d');const to=feed.lastUpdated?.getTime();const window=Number.isFinite(to)?analyticsWindow(period,to):null;
  const activity=useAnalyticsActivity({incidents:feed.reports,from:window?.from??null,to,accountId,enabled:!!window&&!feed.error});
  const data=useMemo(()=>window&&!feed.error?calculateAnalytics(feed.reports,activity.rows,period,to):null,[feed.reports,activity.rows,period,to,feed.error]);
  return <AnalyticsView data={data} period={period} onPeriod={setPeriod} onRefresh={feed.refresh} loading={feed.loading} error={feed.error} activityStatus={activity.status} onSelect={onSelect}/>;
}



